######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 20 18:01:15 2014
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += round.h
SOURCES += area.c circle.c main.c volume.c
