######################################################################
# Automatically generated by qmake (1.07a) Thu Oct 23 21:03:10 2014
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += round.h
SOURCES += area.c circle.c main.c volume.c
